name: Build dotnet 3.1, 5.0, 6.0 & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    env:
      config: 'Release'
    strategy:
      matrix:
        dotnet: ['3.1.x', '5.0.x', '6.0.x']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore Tests/Tests.fsproj
    - name: Build
      run: dotnet build --no-restore Tests/Tests.fsproj
    - name: Test
      run: dotnet test --no-build --verbosity normal Tests/Tests.fsproj
