name: Build Fable & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_js_and_test:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
    strategy:
      matrix:
        dotnet: ['6.0.x']
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'
    - name: Restore tools
      run: dotnet tool restore
    - name: Install
      run: pnpm install
    - name: Test
      run: pnpm test
